const clearMR = [
  {
    Mfr: "AOC",
    "Product/Model Number": "AG276QKD",
    "Screen Size": "27",
    Resolution: "QHD",
    ResolutionCN: "四分之一高清",
    ResolutionType: "2K",
    "Frame Rate": "480Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "AOC",
    "Product/Model Number": "AG276QSD",
    "Screen Size": "26.5",
    Resolution: "QHD",
    ResolutionCN: "四分之一高清",
    ResolutionType: "2K",
    "Frame Rate": "360Hz",
    "ClearMRTM Tier": 18000,
  },
  {
    Mfr: "AOC",
    "Product/Model Number":
      "AG276QZD2AG276QZD SeriesQ27G4Z SeriesAG277QZ SeriesAG276QZD/P",
    "Screen Size": "27",
    Resolution: "QHD",
    ResolutionCN: "四分之一高清",
    ResolutionType: "2K",
    "Frame Rate": "240Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "AOC",
    "Product/Model Number": "PD34 Series",
    "Screen Size": "34",
    Resolution: "UWQHD",
    ResolutionCN: "超宽四分之一高清",
    ResolutionType: "2K",
    "Frame Rate": "240Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "Corsair",
    "Product/Model Number": "Xeneon 27QHD240 OLED",
    "Screen Size": "27",
    Resolution: "QHD",
    ResolutionCN: "四分之一高清",
    ResolutionType: "2K",
    "Frame Rate": "240Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "Corsair",
    "Product/Model Number": "XENEON 27QHD240-A OLED",
    "Screen Size": "27",
    Resolution: "QHD",
    ResolutionCN: "四分之一高清",
    ResolutionType: "2K",
    "Frame Rate": "240Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "Corsair",
    "Product/Model Number": "XENEON FLEX 27QHD240 OLED",
    "Screen Size": "27",
    Resolution: "QHD",
    ResolutionCN: "四分之一高清",
    ResolutionType: "2K",
    "Frame Rate": "240Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "Corsair",
    "Product/Model Number": "XENEON 34WQHD240 OLED",
    "Screen Size": "34",
    Resolution: "UWQHD",
    ResolutionCN: "超宽四分之一高清",
    ResolutionType: "2K",
    "Frame Rate": "240Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "GigaByte",
    "Product/Model Number": "AORUS FO27Q3",
    "Screen Size": "27",
    Resolution: "QHD",
    ResolutionCN: "四分之一高清",
    ResolutionType: "2K",
    "Frame Rate": "360Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "GigaByte",
    "Product/Model Number": "AORUS FO32U2",
    "Screen Size": "31",
    Resolution: "UHD",
    ResolutionCN: "超高清",
    ResolutionType: "4K",
    "Frame Rate": "240Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "GigaByte",
    "Product/Model Number": "AORUS FO32U2P",
    "Screen Size": "31",
    Resolution: "UHD",
    ResolutionCN: "超高清",
    ResolutionType: "4K",
    "Frame Rate": "240Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "GigaByte",
    "Product/Model Number": "MO27Q2",
    "Screen Size": "27",
    Resolution: "QHD",
    ResolutionCN: "四分之一高清",
    ResolutionType: "2K",
    "Frame Rate": "240Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "GigaByte",
    "Product/Model Number": "MO34WQC2",
    "Screen Size": "34",
    Resolution: "UWQHD",
    ResolutionCN: "超宽四分之一高清",
    ResolutionType: "2K",
    "Frame Rate": "240Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "HP",
    "Product/Model Number": "Omen Transcend 32",
    "Screen Size": "32",
    Resolution: "UHD",
    ResolutionCN: "超高清",
    ResolutionType: "4K",
    "Frame Rate": "240Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "Lenovo",
    "Product/Model Number": "A243403Y0",
    "Screen Size": "34",
    Resolution: "UWQHD",
    ResolutionCN: "超宽四分之一高清",
    ResolutionType: "2K",
    "Frame Rate": "240Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "LGE",
    "Product/Model Number": "27GR95QE27GR95QL",
    "Screen Size": "27",
    Resolution: "QHD",
    ResolutionCN: "四分之一高清",
    ResolutionType: "2K",
    "Frame Rate": "240Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "LGE",
    "Product/Model Number": "27GX790A",
    "Screen Size": "27",
    Resolution: "QHD",
    ResolutionCN: "四分之一高清",
    ResolutionType: "2K",
    "Frame Rate": "480Hz",
    "ClearMRTM Tier": 21000,
  },
  {
    Mfr: "LGE",
    "Product/Model Number":
      "32GS95UE32GX870A32GS95UX32GS93UE32GS95UB32GS95UV32GS94UX",
    "Screen Size": "32",
    Resolution: "UHD",
    ResolutionCN: "超高清",
    ResolutionType: "4K",
    "Frame Rate": "240Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "LGE",
    "Product/Model Number": "34GS95QE34GS95QX34GS93QE34GS95QB",
    "Screen Size": "34",
    Resolution: "UWQHD",
    ResolutionCN: "超宽四分之一高清",
    ResolutionType: "2K",
    "Frame Rate": "240Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "LGE",
    "Product/Model Number": "39GS96QB39GS95QE39GS95QX39GS93QE39GS95QB",
    "Screen Size": "39",
    Resolution: "UWQHD",
    ResolutionCN: "超宽四分之一高清",
    ResolutionType: "2K",
    "Frame Rate": "240Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "MSI",
    "Product/Model Number": "MAG 271QP QD-OLED X24",
    "Screen Size": "27",
    Resolution: "QHD",
    ResolutionCN: "四分之一高清",
    ResolutionType: "2K",
    "Frame Rate": "240Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "MSI",
    "Product/Model Number": "MAG 271QPX QD-OLED",
    "Screen Size": "27",
    Resolution: "QHD",
    ResolutionCN: "四分之一高清",
    ResolutionType: "2K",
    "Frame Rate": "360Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "MSI",
    "Product/Model Number": "MAG 271QPX QD-OLED E2",
    "Screen Size": "27",
    Resolution: "QHD",
    ResolutionCN: "四分之一高清",
    ResolutionType: "2K",
    "Frame Rate": "240Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "MSI",
    "Product/Model Number": "MAG 273QP QD-OLED X24",
    "Screen Size": "27",
    Resolution: "QHD",
    ResolutionCN: "四分之一高清",
    ResolutionType: "2K",
    "Frame Rate": "240Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "MSI",
    "Product/Model Number": "MAG 321UPX QD-OLED",
    "Screen Size": "32",
    Resolution: "UHD",
    ResolutionCN: "超高清",
    ResolutionType: "4K",
    "Frame Rate": "240Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "MSI",
    "Product/Model Number": "MPG 271QRX QD-OLED",
    "Screen Size": "27",
    Resolution: "QHD",
    ResolutionCN: "四分之一高清",
    ResolutionType: "2K",
    "Frame Rate": "360Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "MSI",
    "Product/Model Number": "MPG272URX QD-OLED",
    "Screen Size": "27",
    Resolution: "UHD",
    ResolutionCN: "超高清",
    ResolutionType: "4K",
    "Frame Rate": "240Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "MSI",
    "Product/Model Number": "MPG 321URX QD-OLED",
    "Screen Size": "32",
    Resolution: "UHD",
    ResolutionCN: "超高清",
    ResolutionType: "4K",
    "Frame Rate": "240Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "MSI",
    "Product/Model Number": "MPG 341CQPX QD-OLED",
    "Screen Size": "34",
    Resolution: "UWQHD",
    ResolutionCN: "超宽四分之一高清",
    ResolutionType: "2K",
    "Frame Rate": "240Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "Philips",
    "Product/Model Number": "27M2N850027M2N8600 27M2N6500 27M2N6600",
    "Screen Size": "27",
    Resolution: "QHD",
    ResolutionCN: "四分之一高清",
    ResolutionType: "2K",
    "Frame Rate": "360Hz",
    "ClearMRTM Tier": 13000,
  },
  {
    Mfr: "Philips",
    "Product/Model Number": "32M2N8800 Series",
    "Screen Size": "32",
    Resolution: "UHD",
    ResolutionCN: "超高清",
    ResolutionType: "4K",
    "Frame Rate": "240Hz",
    "ClearMRTM Tier": 13000,
  },
];
const resolutionSet = new Set(clearMR.map((item) => item["Resolution"]));
const frameRateSet = new Set(clearMR.map((item) => item["Frame Rate"]));
const clearMRSet = new Set(clearMR.map((item) => item["ClearMRTM Tier"]));
const mfrSet = new Set(clearMR.map((item) => item["Mfr"]));

const list = [];
mfrSet.forEach((mfr) => {
  const arr = [];
  clearMR
    .filter((item) => item["Mfr"] === mfr)
    .forEach((item) => {
      arr.push(item);
    });
  list.push(arr);
});

console.log(list);
